BucHelp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    #calls bucoverflow urls from empty path
    path("", include("BucOverflow.urls")),
    path('admin/', admin.site.urls),
    path('bucoverflow/', include('BucOverflow.urls')),
    
]   + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

BucOverflow/urls.py
from django.urls import path, include

from . import views
from .views import base, discussions, home, about, ourteam, report, SignUpView

app_name = "BucOverflow"

# URL patterns for path navigational information

urlpatterns = [
    path("", views.home, name="base"),
    path("discussions", views.discussions, name="discussions"),
    path("home", views.home, name="home"),
    path("about", views.about, name="about"),
    path("ourteam", views.ourteam, name="ourteam"),
    path("report", views.report, name="report"),
    path("signup", SignUpView.as_view(), name="signup"),
    path("post/<slug>/", views.post, name="post"),
    #path("signup/", views.signup, name="signup"),
    path("signin/", views.signin, name="signin"),
    path("logout/", views.logout, name="logout"),
    path("createpost", views.create_post, name="createpost"),
    path("profile/<slug>/", views.profile, name="profile"),
    path('likepost/', views.like_post, name='like_post'),
    path('dislikepost/', views.dislike_post, name='dislike_post'),
     #url(r'^(?P<slug>[-\w]+)/$', views.post, name='post'),
]

BucOverflow/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime, timedelta
from django.utils.timezone import utc
import math

User = get_user_model()


#Models python file handles model functionality and information requests

@receiver(post_save, sender=User)
def create_user_author(sender, instance, created, **kwargs):
    if created:
        Author.objects.create(user=instance, slug=slugify(instance.username), fullname=instance.first_name+instance.last_name)

class Author(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fullname = models.CharField(max_length=40, blank=True)
    slug = models.SlugField(max_length=400, unique=True, blank=True)
    bio = models.TextField(blank=True,max_length=10000, default='Welcome to my page!')
    karma = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

    def getKarma(self):
        karma=0
        posts=Post.objects.filter(user=self)
        comments=Comment.objects.filter(user=self)
        for post in posts:
            karma += post.karma
        for comment in comments:
            karma += comment.karma

        self.karma = karma




    @property
    def num_posts(self):
        return Post.objects.filter(user=self).count()
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.fullname)
        super(Author, self).save(*args, **kwargs)





class Reply(models.Model):
    #default poster is anon
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    content = models.TextField(blank=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.content[:100]


class Comment(models.Model):
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    content  = models.TextField(blank=True,max_length=10000, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    replies = models.ManyToManyField(Reply, blank=True)
    karma = models.IntegerField(default=0)
    timeElapsed= models.TextField(default="just now")
    #reply_count

    def getTimeElapsed(self):
        now = datetime.utcnow().replace(tzinfo=utc)
        timediff = now - self.created_at
        seconds=math.floor(timediff.total_seconds())

        if seconds < 60:
            self.timeElapsed = str(seconds) + " seconds ago"
        elif seconds < 3600:    #minutes
            minutes = seconds // 60 # // discards fractional remainder
            self.timeElapsed = str(minutes) + " minute ago" if minutes == 1 else str(minutes) + " minutes ago"
        elif seconds < 86400:   #hours
            hours = seconds // 3600
            self.timeElapsed = str(hours) + " hour ago" if hours == 1 else str(hours) + " hours ago"
        else:       #days
            days = seconds // 86400
            self.timeElapsed = str(days) + " day ago" if days == 1 else str(days) + " days ago"


    def __str__(self):
        return self.content[:100]
    

class Post(models.Model):
    title = models.CharField(max_length=100, default='no title')
    #slug is the url
    slug = models.SlugField(max_length=400, unique=True, blank=True)
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    content = models.TextField(blank=True,max_length=10000, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    comments = models.ManyToManyField(Comment, blank=True)

    likes = models.ManyToManyField(Author, blank=True, related_name='likes')
    dislikes = models.ManyToManyField(Author, blank=True, related_name='dislikes')
    karma = models.IntegerField(default=0)
    

    def get_total_likes(self):
        return self.likes.count()

    def get_total_dislikes(self):
        return self.dislikes.count()

    def update_karma(self):
        self.karma = self.likes.count() - self.dislikes.count()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return (
            #f"{self.title}"
            #f"{self.user} "
            f"{self.content[:30]}..."
        )


    def get_url(self):
        return reverse("post", kwargs={
            "slug":self.slug
        })


#class LikePost(models.Model):
    #stores likes in Post
    #related name does a backwards relation from Post back to LikePost
    #basically a Post object with a LikePost object attached to it
#    post = models.OneToOneField(Post, related_name="likes_post", on_delete=models.CASCADE)
#    users = models.ManyToManyField(Author, related_name='requirement_comment_likes')
#    created_at = models.DateTimeField(auto_now_add=True)

#    def __str__(self):
#        return str(self.post.content)[:30] + " Likes: " +str(self.users.count())

BucOverflow/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post

# Forms python fuctionality for user data (Username & Password)
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password',)

# Forms Post dara for model Post
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = {"title","content"}

BucOverflow/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string
from .models import Post, Author
from django.contrib.auth.models import User
from .forms import PostForm
try:
    from django.core.urlresolvers import reverse
except:
    from django.urls import reverse
from . import models
from .forms import SignUpForm
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

##REGISTRATION///LOGIN imports//
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import logout as lt
from django.apps import AppConfig
from django.core.signals import setting_changed


# Create your views here.
# url "" should be the index and show the forum d
# url "post/" + post.title should show the post details

def base(request):
    return render(request, "base.html")

def home(request):
    return render(request, "home.html")

def about(request):
    return render(request, "about.html")

def ourteam(request):
    return render(request, "ourteam.html")

def report(request):
    return render(request, "report.html")

def homeredirect():
    return HttpResponse.request


def profile(request, slug):
    
    #post = Post.objects.filter(slug = slug)
    profile = get_object_or_404(Author, slug=slug) #404 object not found
    karma= 0
    #update users karma
    posts = Post.objects.filter(user=profile)
    for post in posts:
        karma+=post.karma
    profile.karma = karma

    context = { 'profile' : profile,}

    return render(request, "profile.html", context)

def post(request, slug):
    #post = get_list_or_404
     #post = Post.objects.filter(slug = slug)
     post = get_object_or_404(Post, slug=slug) #404 object not found

     context = { 'post' : post,}

     return render(request, "post.html", context)

def discussions(request):
    posts = Post.objects.all()
    postsliked = []
    postsdisliked = []
    if request.user.is_authenticated:  # Notice this condition
        #now get the author or current user
        author = Author.objects.get(user=request.user)
        for post in posts:
            #update karma for posts
            post.update_karma()
            post.save()
            #if user has liked this post
            if post.likes.filter(user=author.user).exists(): #might need to overwrite author equals val
                postsliked.append(post.id) 
            if post.dislikes.filter(user=author.user).exists(): #might need to overwrite author equals val
                postsdisliked.append(post.id) 
            comments = post.comments.all()
            for comment in comments:
                comment.getTimeElapsed()
                comment.save()
    else: #user is not autheticated aka signed in
        for post in posts:
             #update karma for posts
            post.update_karma()
            post.save()
            comments = post.comments.all()
            for comment in comments:
                comment.getTimeElapsed()
                comment.save()

    test=search(posts, "laundry")
    print(test)
    context = { 'posts' : posts,
                'postsliked' : postsliked,
                'postsdisliked' : postsdisliked}
    return render(request, "discussions.html", context)

@login_required
def create_post(request):
    context = {}
    #use to check if our POST is valid
    form = PostForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
             print("\n\n valid post!")
             author = Author.objects.get(user=request.user)
             new_post = form.save(commit=False)
             new_post.user = author
             new_post.save()
             form.save_m2m()
             return redirect("/home")
    context.update({
        "form": form,
        "title": "OZONE: Create New Post"
    })
    return render(request, "create_post.html", context)



#####REGISTRATION///LOGIN####
def signin(request):
    context = {}
    form = AuthenticationForm(request, data=request.POST)
    if request.method == "POST":
        #username = request.POST['username']
        #password = request.POST['password']
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username)
        user = authenticate(request, username=username, password=password)
        if user is not None:
            #sucsess
            login(request, user)
            return redirect("/home")
    context.update({
        "form": form,
        "title": "Signin",
    })
    return render(request, "signin.html", context)

@login_required
def logout(request):
    lt(request)
    return redirect("/home")

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    template_name = "signup.html"
    success_url = reverse_lazy('BucOverflow:home')


#user likes post
@login_required(login_url='/signin/')
def like_post(request):
    #use id from ajax post
    post = get_object_or_404(Post, id=request.POST.get('id')) #404 object not found 

    #now get the author that liked the post
    author = Author.objects.get(user=request.user)

    is_liked = False
    if post.likes.filter(id=author.id).exists():
        post.likes.remove(author)
        is_liked = False
    else:
        post.likes.add(author)
        is_liked = True
        #check if they had it disliked
        if post.dislikes.filter(id=author.id).exists():
            post.dislikes.remove(author)
    post.update_karma()
    post.save()
    #context = { 'posts' : posts,}
    return render(request, "discussions.html")

    #user dislikes post
@login_required(login_url='/signin/')
def dislike_post(request):
    #use id from ajax post
    post = get_object_or_404(Post, id=request.POST.get('id')) #404 object not found 

    #now get the author that liked the post
    author = Author.objects.get(user=request.user)

    is_disliked = False
    if post.dislikes.filter(id=author.id).exists():
        post.dislikes.remove(author)
        is_disliked = False
    else:
        post.dislikes.add(author)
        is_disliked = True
        #check if they had it liked
        if post.likes.filter(id=author.id).exists():
            post.likes.remove(author)
    post.update_karma()
    post.save()
    return render(request, "discussions.html")

#return sorted list
def search(posts, search):
    count = 0
    highestCount = 0
    mostRelevantPost= posts[0]
    temp=""
    for post in posts:
        count = 0
        #for each post object get the number of matches
        for element in post.title:
            #do not exceede search string length
            if(count<len(search)):
                if(search[count] == element):
                    count += 1
        if count > highestCount:
            highestCount = count
            mostRelevantPost = post
            
    return mostRelevantPost

        

BucOverflow/templates/base.html
{% load static %}

<!--
Base.html template defines page standards that all other templates implement.
Standards include headers, navigations, and design standards.
-->

<html lang="en">


<style>

/* Style for footer on site */
.site-footer {
  background: #00003d;
  height: auto;
}

/* Style for site background which includes url */
body {background: url(https://www.etsu.edu/_images/background_images/noise.png) repeat 0 0, radial-gradient(circle at 50% 100%, hsla(0,0%,100%,0.1) 50%, hsla(44,100%,59%,0.1) 66%, hsla(209,36%,54%,0.3) 100%) no-repeat fixed, linear-gradient(to bottom, #ffffff 62%,hsla(44,100%,59%,0.1) 138%) no-repeat fixed;}
  
</style>


<!-- Start of HTML functionality -->

<link rel="stylesheet" type='text/css' href="{% static 'base.css' %}">
<!---Load jquery-->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!--Used for liking/disliking posts and comments-->

<!-- JS script for token post like -->
<script type="text/javascript">
  $(document).ready(function(event){
    $(document).on('click', '#like', function(event){
        event.preventDefault();
        var pk = $(this).attr('value');
        $.ajax({
            type: 'POST',
            url: "{% url 'BucOverflow:like_post' %}",
            data: {
                'id': pk,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(response){
                //$('#like-section').html(response['form'])
            },
            error: function(rs, e){
                console.log(rs.responseText);
            },
        });
    });
  });
</script>

<!-- JS script for token post dislike -->
<script type="text/javascript">
  $(document).ready(function(event){
    $(document).on('click', '#dislike', function(event){
        event.preventDefault();
        var pk = $(this).attr('value');
        $.ajax({
            type: 'POST',
            url: "{% url 'BucOverflow:dislike_post' %}",
            data: {
                'id': pk,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            success: function(response){
                //$('#like-section').html(response['form'])
            },
            error: function(rs, e){
                console.log(rs.responseText);
            },
        });
    });
  });
</script>

<!-- Navigation and background functionality and design -->

  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
  <nav style="background-color: #FFc72c;" class="navbar is-warning" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <!-- Nvigation logo and href-->
    <a class="navbar-item" href="/bucoverflow/home">
      <img src="{% static 'Logo.png' %}" width="112" height="28"> 
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <!-- Navigation bar items and hrefs -->
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">

      <a class="navbar-item" href="/bucoverflow/discussions">
        <!-- Navigate to discussions page -->
        Explore 
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          <!-- Dropdown to multiple selections (3) -->
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item" href="/bucoverflow/about">
            <!-- Navigate to about page -->
            About Us 
          </a>
          <a class="navbar-item" href="/bucoverflow/ourteam">
            <!-- Navigate to ourteam page -->
            Our Team
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item" href="/bucoverflow/report">
            <!-- Navigate to report page -->
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <!-- Navigation bar signup and login functionality -->
    <div class="navbar-end">
      <div class="navbar-item">
        {% if not user.is_authenticated %}
        <div class="buttons">
          <a href="/bucoverflow/signup" class="button is-info">
            <strong>Sign up</strong>
          </a>
          <a class="button is-light" href="/bucoverflow/signin">
            Log in
          </a>
        </div>

        <!-- If user is logged in, there username will display instead -->
        {% else %}
          <a class="navbar-link" href="/profile/{{ user.username }}/">Hello, {{user.username}}!</a>
          <a class="button is-info" href="/bucoverflow/logout"><strong>Log Out</strong></a>
        {% endif %}

      </div>
    </div>
  </div>
</nav>

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Include the Bulma CSS framework for styling-->
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">

<body>

{% block content %}
{% endblock content%}

<!-- Footer design and functionality  -->
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
<a id="return-to-top"><i class="icon-chevron-up"></i></a>

<!-- Background image -->
<img src="{% static 'mountains.svg' %}">
<div style><strong>
  <footer class="site-footer">
    <div class="container">
        <div class="columns">
            <div class="column is-3 is-offset-2">
                <string style="color:white;">Explore</strong>
                <ul>
                  <!-- Navigation to discussions page -->
                    <li><a href="/bucoverflow/discussions">Read and create posts</a></li>
                </ul>
            </div>
            <div class="column is-3">
                <strong style="color:white;">About</strong>
                <ul>
                   <!-- Navigation to about page -->
                    <li><a href="/bucoverflow/about">Learn about our application</a></li>
                </ul>
            </div>
            <div class="column is-4">
                <strong style="color:white;">Our Team</strong>
                <ul>
                   <!-- Navigation to ourteam page -->
                    <li><a href="/bucoverflow/ourteam">Learn about our team</a></li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Script implementations -->
    <script src="../js/bulma.js"></script>
</footer>
</strong></div>
<script src="{% static 'base.js' %}"></script>
</body>
</html>

BucOverflow/templates/create_post.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">


<div class="hero is-fullheight">
<h2 style="text-align:center; margin-block:5px; color:black;">{{user}}, Write something</h1>
<h1 style="text-align:center">Post Creator</h2>
    <div class="hero-body is-justify-content-center is-align-items-center">
        <div class="columns is-flex is-flex-direction-column box">
            <form method="POST" style="margin-left:15px;">
                {% csrf_token %}    
                <div class="column">
                    <label for="title">title</label>
                    <!---name is used for django post--->
                    <input class="input is-primary" name="title" type="title" placeholder="">
                </div>
                <div class="column">
                    <label for="content">content</label>
                    <textarea placeholder="Your content here" name="content" class="input"></textarea>
                </div>
                    
                <input class="button is-primary" type="submit" value="Save"  style="margin-block:50px;">
            </form>
        </div>
    </div>
</div>

{% endblock content %}

BucOverflow/templates/discussions.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<!DOCTYPE html>
<title>BucHelp</title>
<body>
  <link rel="stylesheet" type='text/css' href="{% static 'vote.css' %}">

  <style>



  .previous {
  background-color: #FFc72c;;
  color: black;
  }
  
  .round {
  border-radius: 50%;
  }

    .search-form {
    float: left;
    margin-top: 10px;
    }
  
    .hashtags {
     display: inline-block;
     margin: 5px 0;
    }
  
    .hashtag {
    display: inline-block;
    padding: 3px 5px;
    border-radius: 5px;
    color: #FFF;
    font-size: 14px;
    font-weight: bold;
    margin-right: 5px;
    }

    .wrap {  height: 256px;overflow: hidden; }
    .frame { width: 800px; height: 600px; overflow:hidden}
    .frame {
        -ms-zoom: 0.75;
        -moz-transform: scale(0.25);
        -moz-transform-origin: 0 0;
        -o-transform: scale(0.25);
        -o-transform-origin: 0 0;
        -webkit-transform: scale(0.25);
        -webkit-transform-origin: 0 0;
    }
    
  </style>




  <section style="background-color:  #041E42;"class="hero is-small is-success mb-4">
    <div class="hero-body">
      <a href="/bucoverflow/home" style="text-align:left;float:left; margin-right: 20px; color: black;text-decoration: none;
      display: inline-block;
      padding: 7px 17px;
      margin-top: 0px;" class="previous round">&#8249; </a>
        <h1  class="texteffect title" data-value="Discussions">Discussions</h1>
      
      <form class="search-form">
        <div class="field has-addons">
          <div class="control">
            <input class="input" type="text" placeholder="Find a post">
          </div>
          <div class="control">
            <a class="button is-info">
              Search
            </a>
          </div>
        </div>

        <span class="hashtag" style="background-color: #F44336">Rising</span>
        <span class="hashtag" style="background-color: #E91E63">Controversial</span>
        <span class="hashtag" style="background-color: #9C27B0">Trending</span>
        <span class="hashtag" style="background-color: #673AB7">Top</span>
        <span class="hashtag" style="background-color: #3F51B5">Answered</span>
      </form>
    </div> 
  </section>



  <section class="container">
    <div class="columns">
          <!---Meme of the day microservice-->
            <div class="column is-2">
              <a style="margin-bottom: 25px;"class="button is-primary is-block is-alt is-large" href="/bucoverflow/createpost">New Post</a>
              <div class="box content wrap">
                <h1>Meme of the Day</h1>
                <iframe class="frame" src="https://finalprojectcsci311020230410153042.azurewebsites.net/images/meme2.jpg"></iframe>
              </div>
            </div>



      <div class="column is-9">
        <div class="box content">
          {% for post in posts %}
          <article class="post" style="padding-bottom: 25px;">
            <div class="columns">
              <div class="coulmn is-2">
                <!---LIKE//DISLIKE FORM-->
                {% if user.is_authenticated %}
                  <!--include app name-->
                  <form action="{% url 'BucOverflow:like_post' %}" method="post">
                    {% csrf_token %}
                    {% if post.id in postsliked %} <!--See if user liked post already-->
                    <div style="display: flex; flex-direction: column;">
                      <div id="like" value="{{ post.id }}">
                      <span onclick="like_function({{post.pk}})" id="like-{{post.pk}}" class="vote_up_on"></span></div>
                      <div style="padding-left: 20px;" id="counter-{{post.pk}}"> {{ post.karma }} </div>
                      <div id="dislike" value="{{ post.id }}">
                      <span onclick="dislike_function({{post.pk}})" id="dislike-{{post.pk}}" class="vote_down_off"></span></div>
                    </div>
                    {% elif post.id in postsdisliked %} <!--See if user disliked post already-->
                    <div style="display: flex; flex-direction: column;">
                      <div id="like" value="{{ post.id }}">
                      <span onclick="like_function({{post.pk}})" id="like-{{post.pk}}" class="vote_up_off"></span></div>
                      <div style="padding-left: 20px;" id="counter-{{post.pk}}"> {{ post.karma }} </div>
                      <div id="dislike" value="{{ post.id }}">
                      <span onclick="dislike_function({{post.pk}})" id="dislike-{{post.pk}}" class="vote_down_on"></span></div>
                    </div>
                    {% else %}  <!--User hasnt liked or disliked post-->
                    <div style="display: flex; flex-direction: column;">
                      <!---<span onclick="like_function({{post.pk}})" id="like-{{post.pk}}" class="vote_up_off"></span>--->
                      <!--Div id="like" is used in the AJAX POST request in base.html-->
                      <div id="like" value="{{ post.id }}">
                        <!--Used strictly for client side js-->
                      <span onclick="like_function({{post.pk}})" id="like-{{post.pk}}" class="vote_up_off"></span></div>
                      <div style="padding-left: 20px;" id="counter-{{post.pk}}"> {{ post.karma }} </div>
                      <div id="dislike" value="{{ post.id }}">
                      <span onclick="dislike_function({{post.pk}})" id="dislike-{{post.pk}}" class="vote_down_off"></span></div>
                    </div>
                    {% endif %}
                  </form>
                  <!---USER not signed in-->
                {% else %}
                      <span onclick="location='{% url 'BucOverflow:signin' %}'" id="like" class="vote_up_off"></span>
                      <div style="padding-left: 20px;" id="counter-{{post.pk}}"> {{ post.karma }} </div>
                      <span onclick="location='{% url 'BucOverflow:signin' %}'" id="dislike-{{post.pk}}" class="vote_down_off"></span>
                {% endif %}
              </div>

              <div class="column">
                        <div class="media">
                          <div class="media-left"><p>posted by <a href="profile/{{post.user.slug}}/">{{ post.user }}</a></p></div>
                          <div class="media-content"></div>
                          <div class="media-right"><p>{{ post.created_at }}</p></div>
                        </div>
                        <h4><a href="post/{{post.slug}}/">{{ post.title }}</a> <span class="tag is-primary is-medium ">Question</span> </h4>
                        <p>{{post}}</p>
                        {% if post.comments.all.0 %}
                        <div class="media">
                          <div class="media-left">
                            <p class="image is-32x32">
                              <!---<img src="http://bulma.io/images/placeholders/128x128.png">-->
                              <img style="border-radius: 50%;" src="{% static 'profile.jpg' %}"  width="112" height="112">
                            </p>
                          </div>
                          <div class="media-content">
                            <div class="content">
                              <p>
                                <a href="profile/{{post.comments.all.0.user.slug }}/">{{ post.comments.all.0.user }}</a> replied {{post.comments.all.0.timeElapsed}}  &nbsp;
                                <span class="tag">Question</span>
                              </p>
                            </div>
                          </div>
                          <div class="media-right">
                            <span class="has-text-grey-light"><i class="fa fa-comments"></i> {{ post.comments.all.count }} comment(s)</span>
                          </div>
                        </div>
                        <div class="media"></div>
                        {% else %}
                        <div class="media"></div>
                        <div class="media"></div>
                        {% endif  %}
              </div> <!--Column 7-->
            </div><!--columns 2-->
            </article>
            {% endfor %}
          </div>  <!---Box Content-->
        </div>  <!--Column 9-->
    </div>  <!---Columns-->
  </section>



  <script src="{% static 'vote.js' %}"></script>
  <script src="{% static 'script.js' %}"></script>

</body>
</html>

{% endblock content%}